In [2]:
import numpy as np

In [24]:
   def rle2mask(rle, imgshape):
    width = imgshape[0]
    print(f"Resmin genişliği : {width}")
    height= imgshape[1]
    print(f"Resmin yüksekliği : {height}")
    
    mask= np.zeros( width*height ).astype(np.uint8)
    print(f"Maske resmimiz : {mask}")
    
    array = np.asarray([int(x) for x in rle.split()])
    print(f"RLE kodunun liste dönüştürülmüş hali : {array}")
    starts = array[0::2]
    print(f"RLE kodunda verilen başlangıç indeksleri : {starts}")
    lengths = array[1::2]
    print(f"RLE kodunda verilen uzunluk değerleri : {lengths}")

    current_position = 0
    for index, start in enumerate(starts):
        mask[int(start):int(start+lengths[index])] = 1
        current_position += lengths[index]
        
    return np.flipud( np.rot90( mask.reshape(height, width), k=1 ) )

In [29]:
imgshape = (5,5)
rle = '1 4 11 2'
rle2mask(rle, imgshape)

Resmin genişliği : 5
Resmin yüksekliği : 5
Maske resmimiz : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
RLE kodunun liste dönüştürülmüş hali : [ 1  4 11  2]
RLE kodunda verilen başlangıç indeksleri : [ 1 11]
RLE kodunda verilen uzunluk ölçütleri : [4 2]


array([[0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=uint8)

In [30]:
print(f"RLE kodunun maskeye dönüştürülmüş hali : \n {rle2mask(rle, imgshape)}")

Resmin genişliği : 5
Resmin yüksekliği : 5
Maske resmimiz : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
RLE kodunun liste dönüştürülmüş hali : [ 1  4 11  2]
RLE kodunda verilen başlangıç indeksleri : [ 1 11]
RLE kodunda verilen uzunluk ölçütleri : [4 2]
RLE kodunun maskeye dönüştürülmüş hali : 
 [[0 0 0 0 0]
 [1 0 1 0 0]
 [1 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
